# Generated by Django 4.2.3 on 2023-07-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Params",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Reason", models.CharField(max_length=200)),
                ("Gender", models.IntegerField()),
                ("Age", models.IntegerField()),
                ("Education", models.IntegerField()),
                ("JobAndActivity", models.CharField(max_length=200)),
                ("Financial", models.IntegerField()),
                ("Asset", models.IntegerField()),
                ("Mariage", models.IntegerField()),
                ("Travels", models.IntegerField()),
                ("SibingsInCA", models.BinaryField()),
                ("RejectionHistory", models.BinaryField()),
            ],
        ),
    ]
